/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meetme_pixelation_VideoPreProcessing */

#ifndef _Included_com_meetme_pixelation_VideoPreProcessing
#define _Included_com_meetme_pixelation_VideoPreProcessing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_meetme_pixelation_VideoPreProcessing
 * Method:    nativeEnablePreProcessing
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_meetme_pixelation_VideoPreProcessing_nativeEnablePreProcessing
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
